### ISSUE TITLE
Coders

### ISSUE THREAD

**Issue by FranzSkuffka** [turboMaCk/any-set#6]
An encoder / decoder would be great. PR welcome?

**Comment by turboMaCk** [comment]
Hi @FranzSkuffka not sure if I missed something but I think even regular Set and Dict don't have any decoder simply because it's hard to map it to JSON types so the translation from Array (that doesn't guarantee uniqueness of elements and has significant ordering) isn't that straight forward. I'm not sure if by providing decoder is something that this package should do. Of course, it's likely some people will define those decoders but than they're at least forced to think about this.

**Comment by FranzSkuffka** [comment]
There are encoders and decoders for dicts in the core: https://package.elm-lang.org/packages/elm/json/latest/Json-Decode#dict

My current implementation looks like this and I don't see either a more reasonable mapping nor the problem with non-uniqueness popping up.
```elm
encodeAnySet : (a -> E.Value) -> Set.Any.AnySet comparable a-> E.Value
encodeAnySet encoder =
  Set.Any.toList
  >> E.list encoder

decodeAnySet : (a -> comparable) -> D.Decoder a -> D.Decoder (Set.Any.AnySet comparable a)
decodeAnySet conversion decoder =
  D.map
    (Set.Any.fromList conversion)
    (D.list decoder)
```

**Comment by turboMaCk** [comment]
I see there is a decoder for `Dict String a` but nothing more (apart from `List a` and `Array a`). On the other hand, there is also more generic `Json.Encode.dict` for `Dict k v` which is an interesting design decision. There is also an `encode` for `Set` but no decoder. It seems like a bit messy to me. I'm still unsure how I feel about adding this but let's say we want to add it.

I'm thinking maybe there should be a new module like `Json.Decode.Any` and `Json.Encode.Any` exposing function `set`. What I'm not 100% is what compilers do when 2 packages define the same module. I know during `import .... as` one can smash two namespaces together like `import List.Extra as List` but it might be more problematic when module names itself collide - I will need to test it first.

**Comment by FranzSkuffka** [comment]
Having identical modules in the deps and locally produces a collision. I think `Json.Decode.Any` would be a premature optimizatoin because right now I can only think of `Dict` and `Set` requiring an `Any` version.

**Comment by turboMaCk** [comment]
@FranzSkuffka hey I know a lot of time has passed but I'm actually starting to consider inclusion of encode function and decoder constructor. Are you interested in submitting patch yourself?

**Comment by FranzSkuffka** [comment]
Happy to open a PR. Would you be okay with the code I posted above?

**Comment by turboMaCk** [comment]
@FranzSkuffka I would exclude `AnySet` suffix (I'm expecting usage like `Set.Any.encode` so `Set.Any.encodeAnySet` seems duplicating same information twice) but other than that it seems OK as is. Anyway feel free to do it your way completely so I can see how you would go about that and then we can discuss things together. I think in most cases it's best to first here more opinions and then make the decisions - especially concerning naming.

**Comment by FranzSkuffka** [comment]
The rationale behind this naming is https://github.com/FranzSkuffka/elm-coder-generator which assumes that type names are included in encoder names. However I do see your point - it is more elegant and that is what we should aim for.

**Comment by FranzSkuffka** [comment]
Sorry for the delay :)

**Comment by turboMaCk** [comment]
new version released, thanks again.
